name: SemSegExt
# known open3d ml bugs
num_workers: 0
pin_memory: false
optimizer:
  lr: 0.001
scheduler_gamma: 0.9886
batch_size: 1
val_batch_size: 1
test_batch_size: 1
train_sum_dir: ./logs/train_logs/
eval_sum_dir: ./logs/eval_logs/
main_log_dir: ./logs
max_epoch: 100
save_ckpt_freq: 10
summary:
  record_for: ['train', 'valid']  # visu for debug purposes, leave empty in final run
  max_pts: 15000
  use_reference: false
  max_outputs: 5